common:
  polling_interval: 60
  region: eu-west-2

environments:
  dev:
    thing_name: "dev-beehome196"
    iot_endpoint: "a1gfewiz2jf216-ats.iot.eu-west-1.amazonaws.com"
    cert_path: "/home/oleksandr/certs/certificate_pem-196.pem.crt"
    key_path: "/home/oleksandr/certs/private_key-196.pem.key"
    root_ca_path: "/home/oleksandr/certs/AmazonRootCA1.pem"

  staging:
    thing_name: "staging-thing"
    iot_endpoint: "staging-ats.iot.us-west-2.amazonaws.com"
    cert_path: "./certs/staging/device-cert.pem"
    key_path: "./certs/staging/device-key.pem"
    root_ca_path: "./certs/staging/root-ca.pem"
    polling_interval: 30  # Override common value

  production:
    thing_name: "prod-thing"
    iot_endpoint: "prod-ats.iot.us-west-2.amazonaws.com"
    cert_path: "./certs/prod/device-cert.pem"
    key_path: "./certs/prod/device-key.pem"
    root_ca_path: "./certs/prod/root-ca.pem"

current_environment: dev
